#API keys
app.books.books.apikey=${APP_BOOKS_BOOKS_APIKEY}
app.books.header.apikey=${APP_BOOKS_HEADER_APIKEY}
app.security.blot.apikey=${APP_SECURITY_BLOT_APIKEY}
app.users.users.apikey=${APP_USERS_USERS_APIKEY_SECRET}


app.users.users.api_url=${APP_USERS_USERS_API_URL_SECRET}
app.social.social.api_url=${APP_SOCIAL_SOCIAL_API_URL_SECRET}

#DB connection through Docker
spring.datasource.url=jdbc:mysql://mysql:3306/BPlot_books

#DB authentication provided via docker-compose
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

