spring.application.name=BookMicroservice
server.port=9002

#JPA
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

#Java Melody
javamelody.enabled=true
javamelody.excluded-datasources=secretSource,topSecretSource
javamelody.spring-monitoring-enabled=true
javamelody.init-parameters.log=true
#What we exclude from the url
javamelody.init-parameters.url-exclude-pattern=(/webjars/.*|/css/.*|/images/.*|/fonts/.*|/js/.*)
# javamelody.init-parameters.authorized-users=admin:pwd
# to change the default "/monitoring" path:
# javamelody.init-parameters.monitoring-path=/admin/performance
javamelody.url-pattern=/monitoring/*


