package com.security.security.dto;

import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.Setter;

/**
 * DTO we sent to the frontend with users information
 */
@Getter @Setter @AllArgsConstructor
public class AuthResponseDTO {

    //Response fron the authenticator, token is generated by generateToken()
    private String fullname;
    private String username;
    private String profileImage;
    private String token;

}
