app.security.blot.apikey=${APP_SECURITY_BLOT_APIKEY_SECRET}
app.users.users.apikey=${APP_USERS_USERS_APIKEY_SECRET}

spring.datasource.url=jdbc:mysql://localhost:3306/BPlot_users
spring.datasource.username=${DB_USERNAME_SECRET}
spring.datasource.password=${DB_PASSWORD_SECRET}