spring.application.name=UsersMicroservice
server.port=9001

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

javamelody.enabled=true
javamelody.excluded-datasources=secretSource,topSecretSource
javamelody.spring-monitoring-enabled=true
javamelody.init-parameters.log=true
#lo que se excluye de url
javamelody.init-parameters.url-exclude-pattern=(/webjars/.*|/css/.*|/images/.*|/fonts/.*|/js/.*)
# javamelody.init-parameters.authorized-users=admin:pwd
#  to change the default "/monitoring" path:
# javamelody.init-parameters.monitoring-path=/admin/performance
javamelody.url-pattern=/monitoring/*

#Upload directory for profile images
upload.root-location=${UPLOAD_DIR}





