spring.application.name=UsersMicroservice

server.port=9001

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


javamelody.enabled=true
javamelody.excluded-datasources=secretSource,topSecretSource
javamelody.spring-monitoring-enabled=true
javamelody.init-parameters.log=true
#lo que se excluye de url
javamelody.init-parameters.url-exclude-pattern=(/webjars/.*|/css/.*|/images/.*|/fonts/.*|/js/.*)
# javamelody.init-parameters.authorized-users=admin:pwd
#  to change the default "/monitoring" path:
# javamelody.init-parameters.monitoring-path=/admin/performance
javamelody.url-pattern=/monitoring/*

# Subida de ficheros
upload.root-location=upload-dir

#Habilitar trace en logs (Desabilitar trace y debug en produccion)
logging.level.com.users.UsersMicroservice=TRACE
logging.file.name = users-logs

#Referencia al otro properties de las claves
spring.profiles.active=local

#app.users.users_apikey=${USERS_APIKEY}
#app.security.bplot_apikey=${BPLOT_APIKEY}

