app.security.blot.apikey=${APP_SECURITY_BLOT_APIKEY_SECRET}
app.users.users.apikey=${APP_USERS_USERS_APIKEY_SECRET}
app.users.header.apikey=${APP_USERS_HEADER_APIKEY}

#Connection through Docker
spring.datasource.url=jdbc:mysql://mysql:3306/BPlot_users

#Values provided via docker-compose
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

#S3
#Configuration S3
aws.s3.bucket-name=${AWS_S3_BUCKET}
aws.s3.region=${AWS_S3_REGION}

#Redis
spring.redis.host=${REDIS_HOST}
spring.redis.port=${REDIS_PORT}
spring.cache.type=${CACHE_TYPE}
spring.cache.redis.time-to-live=${TIME_TO_LIVE}

# Broker of Kafka
spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS}

# Topic we will listen
topic.follow-requests=${KAFKA_FOLLOW_REQUEST_TOPIC}
topic.follow-answers=${KAFKA_FOLLOW_ANSWER_TOPIC}

#Groups Kafka
group.users=${USERS_FOLLOW_GROUP}

# Reducing kafka logs to minimum
logging.level.org.apache.kafka=ERROR
logging.level.org.springframework.kafka=ERROR

#Upload directory for profile images
upload.root-location=${UPLOAD_DIR}

#JPA Do not use update in production. Use validate or none
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

# Logs: in Docker, they go to stdout (not to file)
logging.level.com.users.UsersMicroservice=INFO
# logging.file.name : we do not define a file because it goes to stdout
