services:
  ## MySQL
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_existing:/var/lib/mysql
    networks:
      - app-network

  ## Kafka and zookeeper: introduce when needed

  ## Redis
  redis:
    image: redis:7.2-alpine
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - app-network

  ## Social Microservice. Introduce when needed

  ## Book Microservice
  book-service:
    build: ./BookMicroservice
    ports:
      - "9002:9002"
    environment:
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      APP_SECURITY_BLOT_APIKEY: ${APP_SECURITY_BLOT_APIKEY}
      APP_BOOKS_BOOKS_APIKEY: ${APP_BOOKS_BOOKS_APIKEY}
      APP_BOOKS_HEADER_APIKEY: ${APP_BOOKS_HEADER_APIKEY}
      APP_USERS_USERS_APIKEY: ${APP_USERS_USERS_APIKEY}
      APP_USERS_USERS_API_URL_SECRET: ${APP_USERS_USERS_API_URL_SECRET}
      APP_SOCIAL_SOCIAL_API_URL_SECRET: ${APP_SOCIAL_SOCIAL_API_URL_SECRET}
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - mysql
      - redis
    networks:
      - app-network

  ##Users Microservice
  user-service:
    build: ./UsersMicroservice
    ports:
      - "9001:9001"
    environment:
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      APP_SECURITY_BLOT_APIKEY: ${APP_SECURITY_BLOT_APIKEY}
      APP_USERS_USERS_APIKEY: ${APP_USERS_USERS_APIKEY}
      APP_USERS_HEADER_APIKEY: ${APP_USERS_HEADER_APIKEY}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      CACHE_TYPE: ${CACHE_TYPE}
      TIME_TO_LIVE: ${TIME_TO_LIVE}
      KAFKA_BOOTSTRAP_SERVERS: ${KAFKA_BOOTSTRAP_SERVERS}
      KAFKA_FOLLOW_REQUEST_TOPIC: ${KAFKA_FOLLOW_REQUEST_TOPIC}
      KAFKA_FOLLOW_ANSWER_TOPIC: ${KAFKA_FOLLOW_ANSWER_TOPIC}
      UPLOAD_DIR: ${UPLOAD_DIR}
      USERS_FOLLOW_GROUP: ${USERS_FOLLOW_GROUP}
      AWS_S3_BUCKET: ${AWS_S3_BUCKET}
      AWS_S3_REGION: ${AWS_S3_REGION}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - mysql
      - redis
    networks:
      - app-network

  ## Security Microservice
  security-service:
    build: ./security
    ports:
      - "9000:9000"
    environment:
      APP_SECURITY_BLOT_APIKEY: ${APP_SECURITY_BLOT_APIKEY}
      APP_SECURITY_HEADER_APIKEY: ${APP_SECURITY_HEADER_APIKEY}
      APP_USERS_USERS_APIKEY: ${APP_USERS_USERS_APIKEY}
      APP_USERS_USERS_API_URL_SECRET: ${APP_USERS_USERS_API_URL_SECRET}
      SPRING_PROFILES_ACTIVE: docker
    networks:
      - app-network


volumes:
  mysql_existing:
    external: true
    name: 86d81aeed83666fe5a7d455b754e2dc008a3d72ab395f337569346d1b9ac1594

networks:
  app-network:
    driver: bridge
