spring.application.name=security

server.port=9000

javamelody.enabled=true
javamelody.excluded-datasources=secretSource,topSecretSource
javamelody.spring-monitoring-enabled=true
javamelody.init-parameters.log=true
#lo que se excluye de url
javamelody.init-parameters.url-exclude-pattern=(/webjars/.*|/css/.*|/images/.*|/fonts/.*|/js/.*)
# javamelody.init-parameters.authorized-users=admin:pwd
#  to change the default "/monitoring" path:
# javamelody.init-parameters.monitoring-path=/admin/performance
javamelody.url-pattern=/monitoring/*

# Subida de ficheros
upload.root-location=upload-dir

#Habilitar trace en logs
logging.level.com.security.security=TRACE
logging.file.name = security-logs

#Referencia al otro properties de las claves
spring.profiles.active=local

#app.security.bplot_apikey=${BPLOT_APIKEY}
#app.users.users_apikey=${USERS_APIKEY}