spring.application.name=security
server.port=9000

javamelody.enabled=true
javamelody.excluded-datasources=secretSource,topSecretSource
javamelody.spring-monitoring-enabled=true
javamelody.init-parameters.log=true
#lo que se excluye de url
javamelody.init-parameters.url-exclude-pattern=(/webjars/.*|/css/.*|/images/.*|/fonts/.*|/js/.*)
# javamelody.init-parameters.authorized-users=admin:pwd
#  to change the default "/monitoring" path:
# javamelody.init-parameters.monitoring-path=/admin/performance
javamelody.url-pattern=/monitoring/*

#Referencia al otro properties de las claves
#spring.profiles.active=local

